# Generated by Django 5.0.1 on 2024-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
