# Generated by Django 5.0.1 on 2024-01-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_active_usertype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_update_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(default=None),
        ),
    ]
