# Generated by Django 5.0.1 on 2024-05-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
    ]
