# Generated by Django 5.0.1 on 2024-05-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
    ]
