# Generated by Django 5.0.1 on 2024-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_context_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
